name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

filter-by-commitish: false

version-resolver:
  major:
    labels: ['breaking-change', 'semver:major']
  minor:
    labels: ['feature', 'feat', 'enhancement', 'semver:minor']
  patch:
    labels: ['bug', 'fix', 'chore', 'refactor', 'semver:patch']
  default: patch

categories:
  - title: '✨ Nové funkce'
    labels: ['feature', 'feat', 'enhancement']
  - title: '🐛 Opravy chyb'
    labels: ['bug', 'fix']
  - title: '🧹 Refaktoring / Údržba'
    labels: ['refactor', 'chore', 'maintenance']
  - title: '📝 Dokumentace'
    labels: ['docs', 'documentation']
  - title: '🧪 Testy'
    labels: ['test', 'tests']
  - title: '⚠️ Breaking changes'
    labels: ['breaking-change', 'semver:major']

autolabeler:
  - label: "feature"
    branch:
      - "/^feat\\//"
      - "/^feature\\//"
    title:
      - "/^feat(\\(.+\\))?:/i"
  - label: "fix"
    branch: ["/^fix\\//", "/^bug\\//"]
    title: ["/^fix(\\(.+\\))?:/i"]
  - label: "chore"
    branch: ["/^chore\\//"]
    title: ["/^chore(\\(.+\\))?:/i"]
  - label: "docs"
    branch: ["/^docs\\//"]
    title: ["/^docs(\\(.+\\))?:/i"]
  - label: "breaking-change"
    title: ["/!:/"]

exclude-labels:
  - 'skip-changelog'

change-template: |
  - $TITLE (#$NUMBER) @$AUTHOR
    $BODY

change-title-escapes: '\<*_&'

replacers:
  - search: "/^(feat|fix|chore|docs|refactor|test|bug|fix|enhancement|enhance)(\\(.+\\))?:\\s*/i"
    replace: ""

sort-by: merged_at
sort-direction: descending

exclude-contributors:
  - "dependabot[bot]"
  - "renovate[bot]"

header: |
  ## Co je nového

template: |
  $CHANGES

footer: |
  ---
  ## 📦 Technické
  - Verze integrace: `v$RESOLVED_VERSION`
  - Minimální verze Home Assistant: `2025.9+`
  - Předchozí tag: `$PREVIOUS_TAG`
  - Autoři přispěli: $CONTRIBUTORS
