name: Release Drafter (dev)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    types: [opened, reopened, synchronize, labeled, unlabeled, edited, closed]

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update draft release for dev
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
