name: Build & Attach ZIP asset
on:
  release:
    types: [published]

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          mkdir -p dist
          zip -r dist/bakalari-ha.zip custom_components/bakalari -x "*/__pycache__/*"

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/bakalari-ha.zip
