name: Validate (hassfest & HACS)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files_ignore: |
            README.md
            .gitignore
            .pre-commit-config.yaml
          files: custom_components/bakalari/**

      - name: Run hassfest if files changed
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: home-assistant/actions/hassfest@master
        with:
          path: custom_components/bakalari

  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration